### ISSUE TITLE
Issue : NoClassDefFoundError with selenium/remote/http/W3CHttpCommandCodec

### ISSUE THREAD

**Issue by 77ripdrive** [appium/java-client#1273]
## The problem

When I try to use Selenium 4 in my test case, the error java.lang.NoClassDefFoundError occurs: org / openqa / selenium / remote / http / W3CHttpCommandCodec.

## Environment

* Appium  app version  that exhibits the issue: 1.15.1
 *Appium version : 'io.appium', name: 'java-client', version: '7.3.0'
* Selenium version : 'selenium-java', version: '4.0.0-alpha-3'
* Last Selenium version that did not exhibit the issue : 'selenium-java', version: '3.141.59'
* Desktop OS/version used to run Appium: Win 10
* Node.js version (unless using Appium.app|exe):
* Npm or Yarn package manager: Gradle 6.0.1
* Mobile platform/version under test:Android 8
* Real device or emulator/simulator:Emulator
*
* 
## Details
When I try to use Selenium 4 in my test case, the error java.lang.NoClassDefFoundError occurs: org / openqa / selenium / remote / http / W3CHttpCommandCodec.
When using earlier dependencies Selenium up to 4 such errors do not occur.
How can this be due to changes in the implementation of Selenium 4?!

## Link to Appium logs
https://gist.github.com/77ripdrive/8007368e8e65bebfad8189a6564f2b9d

## Code To Reproduce Issue [ Good To Have ]
https://github.com/77ripdrive/Mobile-Emulators  

This is a working example with Selenium 3. To reproduce the error, you need to change the version of the dependency in the file build.gradle  line 25  : 
implementation group: 'org.seleniumhq.selenium', name: 'selenium-java', version: '3.141.59'
to the dependency version : 
implementation group: 'org.seleniumhq.selenium', name: 'selenium-java', version: '4.0.0-alpha-3'

**Comment by valfirst** [comment]
@77ripdrive here is a dependency compatibility matrix:

|Appium Java client|Selenium Java client| 
|------------------|--------------------| 
| 7.3.0            | 3.141.59           |
| 7.2.0            | 3.141.59           |
| 7.1.0            | 4.0.0-alpha-1      |
| 7.0.0            | 3.141.59           |

The version of Selenium Java client was downgraded in `7.2.0`: https://github.com/appium/java-client/commit/f5470d9cf355e56023f4a14dba4e80af5ea840fc. The reason is users complains: https://twitter.com/imalittletester/status/1162297550713622529.

Moreover Appium Java client is not compatible with Selenium Java client of versions 4.0.0-alpha-2, 4.0.0-alpha-3 because of this change: https://github.com/SeleniumHQ/selenium/commit/96fec3ca49a1462c7881fcd0c06194cb565bdd2d#diff-fa76272f866d8067bb11a32f27773026

**Comment by 77ripdrive** [comment]
Thanks. When Appium plans to support new features from Selenium 4.

**Comment by valfirst** [comment]
@77ripdrive Selenium 4 is still in alpha, just curious: which particular features from Selenium 4 are you interested in?

**Comment by 77ripdrive** [comment]
👍  :)  I tried to screw Relative Locators , it was interesting to see ..... 
type -> toLeftOf() or toRightOf() or above() or below() or near()   .

**Comment by acarvalhomatos** [comment]
@valfirst hi there, i need to get selenium 4 alpha 2 working with appium to get edge chromium testing. any plans on new updates?

**Comment by valfirst** [comment]
@acarvalhomatos the alpha selenium java client was [reverted](https://github.com/appium/java-client/commit/f4cdaf7821d368e9eefbdffefdc9d7fd03a7ae65) in 7.2.0. (https://twitter.com/imalittletester/status/1162297550713622529)

regarding updates it's better to ask @SrinivasanTarget, @mykola-mokhnach, @KazuCocoa

**Comment by mykola-mokhnach** [comment]
There are no plans to incorporate alpha versions of selenium into stable java client releases.

**Comment by nocomply78** [comment]
@mykola-mokhnach, @SrinivasanTarget , @KazuCocoa 
Are there any plans to support beta versions of Selenium - perhaps in beta versions of Appium? (there's at least one improvement in 4.0.0-beta-4 that I would like to make use of in my test framework)
