### ISSUE TITLE
findElementByAccessibilityId() doesn't accept Name as parameter on Android

### ISSUE THREAD

**Issue by Fanch-** [appium/java-client#158]
*The name locator strategy has been deprecated and will be removed. Please use the accessibility id locator strategy instead.*

Problem : using findElementByAccessibilityId() works great on iOS but not with Android (it accepts only content-desc attribute).

**java-client version : 2.1.0
appium : 1.3.5**

Could you tell me at the same time which selectors are the fastest to use ? (if there is a significant difference) Between AndroidUiAutomator-IosUiAutomation / findElementByAccessibilityID and webdriver locators.

**Comment by Jonahss** [comment]
AccessibilityId is the best way of finding elements. It makes sure you get the exact element you wanted and has the added benefit of improving your app for handicapped users.

The speed of finding elements isn't really affected by the selector used, except that XPath selectors are slowest (because there's parsing to do).

But for queries where AccessibilityId isn't practical, XPath is the most supported and most versatile way to address them.

**Comment by Jonahss** [comment]
Also,  `content-desc` is the way that Android implements accessibility. 
https://developer.android.com/guide/topics/ui/accessibility/apps.html
