### ISSUE TITLE
Not able to search webelements using findElementByAndroidUIAutomator, This method gives compile time error

### ISSUE THREAD

**Issue by amitjaincoer191** [appium/java-client#200]
List[WebElement] LifeStyle_Categories = _driver.findElementsByAndroidUIAutomator("resourceId(\"com.flipkart.android:id/expandable_cat_cell_text\")");
Above statement returns list of webelements, debugged and found it return 19 web elements
Now i picked Ist webelement an try to check is clickable attribute of node is false

WebElement elem = LifeStyle_Categories.get(1);

// ** Below  statement gives compile time error *** //
elem.findElementByAndroidUIAutomator("new UiSelector().clickable(false)"); 

This should not give compile time error
I got definition of above methods from below official url of appium

http://appium.github.io/java-client/io/appium/java_client/FindsByAndroidUIAutomator.html#findElementByAndroidUIAutomator(java.lang.String)

**Comment by Jonahss** [comment]
What's the compile-time error?

**Comment by amitjaincoer191** [comment]
Compile time error:
   The method findElementByAndroidUIAutomator(String) is undefined for the type WebElement

Eclipse suggest below solution but it fails at run time ....
WebElement elem = ((FindsByAndroidUIAutomator) LifeStyle_Categories.get(i)).findElementByAndroidUIAutomator("new UiSelector().clickable(false)");

**Comment by amitjaincoer191** [comment]
Please Any updates on this issue ???

Ideally selenium getAttribute() method should work for all the attributes we see for a Node inside UIAutomator like  clickable,checkable,enabled,focusable,index. It will really solve lot of problems...
and enhance power of appium

In my scenario I need to scroll and verify the list of product types available with the ecommerce site 
Category , Subcategory etc
But Category and Subcategory only differ in attribute "clickable" so during scroll I cannot verify it as I am not able to access "clickable" attribute ...

Thankyou for bearning with me...

**Comment by amitjaincoer191** [comment]
I see same issue here also in  below mentioned tests

https://github.com/appium/java-client/blob/master/src/test/java/io/appium/java_client/android/AndroidGestureTest.java
// findElement,findElementByClassName method returns WebElement but they are assigned to a MobileElement about which compiler complaints and ask for type cast ......

@Test
  public void elementGestureTest(){
	  driver.manage().timeouts().implicitlyWait(2, TimeUnit.SECONDS);
	  MobileElement e = driver.findElement(MobileBy.AccessibilityId("App"));
	  e.tap(1, 1500);
    System.out.println("tap");
	  MobileElement e2 = driver.findElementByClassName("android.widget.TextView");
	  e2.zoom();
    System.out.println("zoom");
    e2.swipe(SwipeElementDirection.RIGHT,1000);
    System.out.println("RIGHT");
}

**Comment by amitjaincoer191** [comment]
Hello, Please help ....

**Comment by Jonahss** [comment]
Oh, so you get the same compilation error in those tests?

What version of Selenium jar are you using? This sounds like an issue in your dependency management for java.

**Comment by amitjaincoer191** [comment]
Hello Jonahss,

Thankyou for reply.

I am using selenium stand alone server 2.45 jar.

My main issue is 
1. If I create a list of webelements as mentioned below
List[WebElement] LifeStyle_Categories = _driver.findElementsByAndroidUIAutomator("resourceId(\"com.flipkart.android:id/expandable_cat_cell_text\")");

2. Using step 1 I got 19 web elements , now I am trying to found that out of 19 elements which elements are clickable, So I applied method findElementByAndroidUIAutomator on above found webelements  some thing like mentioned below

// Checking first element if it is clickable
LifeStyle_Categories.get(1).findElementByAndroidUIAutomator("new UiSelector().clickable(false)");

But this statement gives compile time error in eclipse as mentioned below
The method findElementByAndroidUIAutomator(String) is undefined for the type WebElement

Any specific reason why we cannot use "findElementByAndroidUIAutomator" on webelements

**Comment by Jonahss** [comment]
Ah! You should cast the WebElements to MobileElement class. Then you will
get those methods :)

**Comment by shabana-parveen** [comment]
when I try to scroll the screen in my app, nothing happened even not receiving any exception

I use below piece of code to achieve scroll using java-client 4.1.2 version 

**((AndroidDriver) driver).findElementByAndroidUIAutomator("new UiScrollable(new UiSelector().scrollable(true).instance(0)).scrollIntoView(new UiSelector().textContains(\""+text+"\").instance(0))");**

please refer below appium logs:

[MJSONWP] Responding to client with driver.setValue() result: true
[HTTP] <-- POST /wd/hub/session/d5942964-8c74-4e0f-9611-39522a11fbbf/element/2/value 200 5502 ms - 76 
[HTTP] --> POST /wd/hub/session/d5942964-8c74-4e0f-9611-39522a11fbbf/element {"using":"-android uiautomator","value":"new UiScrollable(new UiSelector().scrollable(true).instance(0)).scrollIntoView(new UiSelector().textContains(\"Register\").instance(0))"}
[MJSONWP] Calling AppiumDriver.findElement() with args: ["-android uiautomator","new UiScrollable(new UiSelector().scrollable(true).instance(0)).scrollIntoView(new UiSelector().textContains(\"Register\")...
[debug] [BaseDriver] Waiting up to 0 ms for condition
[debug] [AndroidBootstrap] Sending command to android: {"cmd":"action","action":"find","params":{"strategy":"-android uiautomator","selector":"new UiScrollable(new UiSelector().scrollable(true).instance(0)).scrollIntoView(new UiSelector().textContains(\"Register\").instance(0))","context":"","multiple":false}}
[AndroidBootstrap] [BOOTSTRAP LOG] [debug] Got data from client: {"cmd":"action","action":"find","params":{"strategy":"-android uiautomator","selector":"new UiScrollable(new UiSelector().scrollable(true).instance(0)).scrollIntoView(new UiSelector().textContains(\"Register\").instance(0))","context":"","multiple":false}}
[AndroidBootstrap] [BOOTSTRAP LOG] [debug] Got command of type ACTION
[AndroidBootstrap] [BOOTSTRAP LOG] [debug] Got command action: find
[AndroidBootstrap] [BOOTSTRAP LOG] [debug] Finding new UiScrollable(new UiSelector().scrollable(true).instance(0)).scrollIntoView(new UiSelector().textContains("Register").instance(0)) using ANDROID_UIAUTOMATOR with the contextId: multiple: false
[AndroidBootstrap] [BOOTSTRAP LOG] [debug] Parsing scrollable: new UiScrollable(new UiSelector().scrollable(true).instance(0)).scrollIntoView(new UiSelector().textContains("Register").instance(0))
[AndroidBootstrap] [BOOTSTRAP LOG] [debug] UiSelector coerce type: boolean arg: true
[AndroidBootstrap] [BOOTSTRAP LOG] [debug] UiSelector coerce type: int arg: 0
[AndroidBootstrap] [BOOTSTRAP LOG] [debug] UiScrollable invoking method: public boolean com.android.uiautomator.core.UiScrollable.scrollIntoView(com.android.uiautomator.core.UiObject) throws com.android.uiautomator.core.UiObjectNotFoundException args: new UiSelector().textContains("Register").instance(0),
[AndroidBootstrap] [BOOTSTRAP LOG] [debug] UiScrollable coerce type: class com.android.uiautomator.core.UiObject arg: new UiSelector().textContains("Register").instance(0)
[AndroidBootstrap] [BOOTSTRAP LOG] [debug] UiSelector coerce type: class java.lang.String arg: "Register"
[AndroidBootstrap] [BOOTSTRAP LOG] [debug] UiSelector coerce type: int arg: 0
[AndroidBootstrap] [BOOTSTRAP LOG] [debug] Method name: scrollIntoView
[AndroidBootstrap] [BOOTSTRAP LOG] [debug] Setting uiObject for scrollIntoView
[AndroidBootstrap] [BOOTSTRAP LOG] [debug] Using: UiSelector[CONTAINS_TEXT=Register, INSTANCE=0]
[AndroidBootstrap] [BOOTSTRAP LOG] [debug] Returning result: {"status":0,"value":{"ELEMENT":"3"}}
[debug] [AndroidBootstrap] Received command result from bootstrap
[MJSONWP] Responding to client with driver.findElement() result: {"ELEMENT":"3"}
[HTTP] <-- POST /wd/hub/session/d5942964-8c74-4e0f-9611-39522a11fbbf/element 200 85 ms - 87 
[BaseDriver] Shutting down because we waited 60 seconds for a command
[debug] [AndroidDriver] Shutting down Android driver
[Appium] Closing session, cause was 'New Command Timeout of 60 seconds expired. Try customizing the timeout using the 'newCommandTimeout' desired capability'
[Appium] Removing session d5942964-8c74-4e0f-9611-39522a11fbbf from our master session list
[debug] [ADB] Getting connected devices...
[debug] [ADB] 1 device(s) connected
[debug] [ADB] Running /Users/f2849/android-sdks/platform-tools/adb with args: ["-P",5037,"-s","192.168.56.101:5555","shell","am","force-stop","com.net.shine"]
[debug] [ADB] Pressing the HOME button
[debug] [ADB] Getting connected devices...
[debug] [ADB] 1 device(s) connected
[debug] [ADB] Running /Users/f2849/android-sdks/platform-tools/adb with args: ["-P",5037,"-s","192.168.56.101:5555","shell","input","keyevent",3]
[debug] [Logcat] Stopping logcat capture
[debug] [AndroidBootstrap] Sending command to android: {"cmd":"shutdown"}
[AndroidBootstrap] [BOOTSTRAP LOG] [debug] Got data from client: {"cmd":"shutdown"}
[AndroidBootstrap] [BOOTSTRAP LOG] [debug] Got command of type SHUTDOWN
[AndroidBootstrap] [BOOTSTRAP LOG] [debug] Returning result: {"status":0,"value":"OK, shutting down"}
[AndroidBootstrap] [BOOTSTRAP LOG] [debug] Closed client connection
[debug] [AndroidBootstrap] [UIAUTO STDOUT] INSTRUMENTATION_STATUS: numtests=1
[debug] [AndroidBootstrap] [UIAUTO STDOUT] INSTRUMENTATION_STATUS: stream=.
[debug] [AndroidBootstrap] [UIAUTO STDOUT] INSTRUMENTATION_STATUS: id=UiAutomatorTestRunner
[debug] [AndroidBootstrap] [UIAUTO STDOUT] INSTRUMENTATION_STATUS: test=testRunServer
[debug] [AndroidBootstrap] [UIAUTO STDOUT] INSTRUMENTATION_STATUS: class=io.appium.android.bootstrap.Bootstrap
[debug] [AndroidBootstrap] [UIAUTO STDOUT] INSTRUMENTATION_STATUS: current=1
[debug] [AndroidBootstrap] [UIAUTO STDOUT] INSTRUMENTATION_STATUS_CODE: 0
[debug] [AndroidBootstrap] [UIAUTO STDOUT] INSTRUMENTATION_STATUS: stream=
[debug] [AndroidBootstrap] [UIAUTO STDOUT] Test results for WatcherResultPrinter=.
[debug] [AndroidBootstrap] [UIAUTO STDOUT] Time: 78.012
[debug] [AndroidBootstrap] [UIAUTO STDOUT] OK (1 test)
[debug] [AndroidBootstrap] [UIAUTO STDOUT] INSTRUMENTATION_STATUS_CODE: -1
[debug] [AndroidBootstrap] Received command result from bootstrap
[debug] [UiAutomator] Shutting down UiAutomator
[debug] [UiAutomator] Moving to state 'stopping'
[debug] [UiAutomator] UiAutomator shut down normally
[deb
