### ISSUE TITLE
replace keyEvent with pressKeyCode

### ISSUE THREAD

**Issue by Jonahss** [appium/java-client#208]
https://github.com/appium/appium/issues/5285#issuecomment-113820748

**Comment by KateOgar** [comment]
waiting fix of this issue asap. May be there are some updates on it?

**Comment by Jonahss** [comment]
Thanks for bringing it to our attention. Is this blocking you?

I might be able to get to it this week. Are you interested in looking at the code and submitting a pull request? The relevant code shouldn't be very complex.

**Comment by KateOgar** [comment]
Thanks for quick answer!
Yep, it's really blocker for us. I'm was waiting long time for fixing this issue, because we can't tap on search button on keyboard in our tests. And I tried to up this issue also here: https://discuss.appium.io/t/unable-to-tap-search-button-on-android-softkeyboard/1598/13

Unfortunately I'm only junior in programming and not sure that i'm able to open PR for fixing this issue, but we are waiting it very much.

**Comment by aniket-21** [comment]
I will create a pull request for this

**Comment by bgordon-applause** [comment]
Any status on this?  I definitely need this to use the SEARCH key on android tablets.  Thanks!

**Comment by aniket-21** [comment]
I have created a pull request...waiting for it to be pulled

**Comment by bgordon-applause** [comment]
Thanks @aniket-21 , I'll look forward to it!

**Comment by Jonahss** [comment]
closed by #233
Will publish new version shortly.
