### ISSUE TITLE
Make AppiumDriver page factory/objects compatible

### ISSUE THREAD

**Issue by abhinavn** [appium/java-client#22]
Currently AppiumDriver doesn't support page factory or objects?

Any workaround with this?

Thanks

**Comment by samsonbarukula** [comment]
how to initialize iosDriver for POM
can you pls give example

**Comment by saikrishna321** [comment]
@samsonbarukula https://github.com/appium/java-client/blob/master/src/test/java/io/appium/java_client/pagefactory_tests/IOSPageFactoryTest.java

**Comment by samsonbarukula** [comment]
Can you please show / send the path of the class from where this IOSPageFactoryTest.java is called...

**Comment by samsonbarukula** [comment]
thank you sai...

**Comment by samsonbarukula** [comment]
When I am executing  IOSPageFactoryTest through junit it is giving the below error for ios11 real device:
 Nov 21, 2017 8:19:23 PM org.openqa.selenium.remote.ProtocolHandshake createSession
INFO: Detected dialect: OSS

can you help pls

**Comment by conan55** [comment]
We gave up on appium 3 years ago after  iOS8. Appium failed miserably.
Eggplant is a better solution.


Sent from my Verizon, Samsung Galaxy smartphone
-------- Original message --------From: Samson <notifications@github.com> Date: 11/21/17  6:12 AM  (GMT-08:00) To: appium/java-client <java-client@noreply.github.com> Cc: conan55 <conan55@pacbell.net>, Comment <comment@noreply.github.com> Subject: Re: [appium/java-client] Make AppiumDriver page factory/objects compatible (#22) 
Can you please show / send the path of the class from where this IOSPageFactoryTest.java is called...

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/appium/java-client","title":"appium/java-client","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/appium/java-client"}},"updates":{"snippets":[{"icon":"PERSON","message":"@samsonbarukula in #22: Can you please show / send the path of the class from where this IOSPageFactoryTest.java is called..."}],"action":{"name":"View Issue","url":"https://github.com/appium/java-client/issues/22#issuecomment-346038033"}}}
