### ISSUE TITLE
DriverServiceSample.java > GeneralServerFlag.APP compilation error

### ISSUE THREAD

**Issue by vikramvi** [appium/java-client#415]
## Description
1. With appium java client version 4.0.0.
2. DriverServiceSample.java has compilation error for GeneralServerFlag.APP "APP can't be resolved or it's not a field"

I referred to 
https://github.com/appium/java-client/blob/master/src/main/java/io/appium/java_client/service/local/flags/GeneralServerFlag.java

http://appium.github.io/java-client/io/appium/java_client/service/local/flags/GeneralServerFlag.html

Observed that APP is not more valid , in that case which property to use ?

## Environment

* java client build version: 1.8.0
* Appium server version : 1.5.0
* Node version: 5.7.0

## Details
NA

## Code To Reproduce Issue [ Good To Have ]

NA

## Ecxeption stacktraces

NA

## Link to Appium logs

NA

**Comment by saikrishna321** [comment]
@vikramvi can you pls point out the location of DriverServiceSample.java?

**Comment by TikhomirovSergey** [comment]
@vikramvi @saikrishna321 
The using of capabilities is correct
https://github.com/appium/java-client/blob/master/src/main/java/io/appium/java_client/remote/MobileCapabilityType.java#L62

You can pass it through constructors of AndroidDriver/IOSDriver or set it as server capabilities. How? 
Please take a look at:
https://github.com/appium/java-client/blob/master/src/test/java/io/appium/java_client/localserver/StartingAppLocallyTest.java

The app flag is deprecated since Appium v1.5.0

Samples are needed to be sync with v4.0.0.

**Comment by vikramvi** [comment]
@saikrishna321 https://github.com/appium/sample-code/blob/master/sample-code/examples/java/junit/src/test/java/com/saucelabs/appium/driver_service/DriverServiceSample.java

Please find this link.

@TikhomirovSergey  I'm trying to fix scripts per latest versions and submit PR in coming days. Will check the examples you mentioned and get back in case of any further doubts.
