### ISSUE TITLE
How to extends from MobileElement

### ISSUE THREAD

**Issue by HlebHalkouski** [appium/java-client#433]
I would like to create TypifiedMobileElement and I was extends from io.appium.java_client.MobileElement : 
`public class MobileElement extends io.appium.java_client.MobileElement {
}`
and then I had compilation exception: 
`Error:(32, 8) java: findElements(org.openqa.selenium.By) in io.appium.java_client.MobileElement cannot implement findElements(org.openqa.selenium.By) in org.openqa.selenium.WebElement
  return type java.util.List<io.appium.java_client.MobileElement> is not compatible with java.util.List<org.openqa.selenium.WebElement>` 

java client: 4.0

Can we extends from MobileElement? 
Thanks for the answer

**Comment by TikhomirovSergey** [comment]
@HlebHalkouski This issue has been fixed.
FIX: #413
Related issues: #362, #220, #323
Please wait for a the new release

**Comment by HlebHalkouski** [comment]
@TikhomirovSergey thank you for fast answer!

**Comment by tfcardoso** [comment]
@SrinivasanTarget @TikhomirovSergey 

In order to try and extend MobileElement I already tried to set  "Eclipse compiler" in IDEA and edited by pom.xml as suggested in here (https://github.com/appium/java-client/issues/220#issuecomment-125033389)

But still I'm getting errors for return types being incompatible. Can you help me on how to proceed?

Thanks
