### ISSUE TITLE
isDisplayed returns true even if Element is not visible on UI

### ISSUE THREAD

**Issue by VenkateshPS** [appium/java-client#619]
## Description
on Android 
isDisplayed returns true even if Element is not visible on UI.

driver.findElementByName(XX).isDisplayed()
uiautomator also displays that element is present.

## Environment

Appium 1.4.13
javaclient 3.4.1

## Details

Please provide more details, if necessary.

**Comment by SrinivasanTarget** [comment]
@VenkateshPS We don't support old version of appium server and client any more. So i would suggest to use latest versions of server and client always. w.r.t visibility it's known issue at times under the hood android/iOS native frameworks appium uses gives it as true. so try to use the attribute visible in your locator strategy and find the element instead of isDisplayed()
