### ISSUE TITLE
5.0.2 - driver.getCapabilities().getCapability("platformName") returns wrong value on Mac

### ISSUE THREAD

**Issue by welnanick** [appium/java-client#719]
## Description
In 5.0.2 the line `driver.getCapabilities().getCapability("platformName")` returns `MAC` when testing an iOS device on a Mac, while `driver.getPlatformName()` returns the expected value `iOS`

## Environment

* java client build version or git revision if you use some shapshot: 5.0.2
* Appium server version or git revision if you use some shapshot: 1.7.0-beta
* Desktop OS/version used to run Appium if necessary: macOS Sierra 10.12.6
* Node.js version (unless using Appium.app|exe) or Appium CLI or Appium.app|exe: 8.4.0
* Mobile platform/version under test: iOS 10.3.2
* Real device or emulator/simulator: Real Device

## Code To Reproduce Issue [ Good To Have ]
Run this code when connected to a real device to see the difference in what's returning.

```
System.out.println(driver.getCapabilities().getCapability("platformName"));
System.out.println(driver.getPlatformName());
```

**Comment by SrinivasanTarget** [comment]
https://github.com/appium/appium/issues/9128

**Comment by welnanick** [comment]
Alright, good to know. Why does `driver.getPlatformName()` return `iOS` still?

**Comment by SrinivasanTarget** [comment]
Will investigate and update you.

**Comment by TikhomirovSergey** [comment]
@SrinivasanTarget @welnanick It is the normal behaviour. 

`driver.getCapabilities().getCapability("platformName")` is the native selenium method that has its own logic.  It seems it returns the value of the CURRENT PLATFORM there the test is started. This is the element of the enum `org.openqa.selenium.Platform`. It is converted from the string value at the moment when a driver instance is created.

`driver.getPlatformName()` returns data of the CURRENT SEESSION. And it is correct because it is the session of an iOS device/Simulator.

**Comment by welnanick** [comment]
@TikhomirovSergey so `driver.getPlatformName()` will not change what it returns?

**Comment by TikhomirovSergey** [comment]
@welnanick No. Session dada is not mutable as I know.

**Comment by welnanick** [comment]
Alrighty. I'll close this issue since it was expected behavior.

**Comment by TikhomirovSergey** [comment]
@welnanick
My reply,
>No. Session data is not mutable as I know.

I was a bit wrong. Some parameters may be changed on the switching from the NATIVE_CONTEXT to WEB_VIEW and back. But `driver.getPlatformName()` returns the value which may be considered as the constant for the certain AppiumDriver instance.
