### ISSUE TITLE
How to identify current iOS screen (activity)?

### ISSUE THREAD

**Issue by TikhomirovSergey** [appium/java-client#87]
Hello!

Is there way to identify current iOS screen (or activity, I am new for iOS) by Appium?

For example.
I can recognize current page by its URL

``` java
driver.getCurrentUrl()
```

Android activity: 

``` java
((AppiumDriver) driver).currentActivity()
```

What can I use against iOS? Both getCurrentUrl() and currentActivity() don't work.
Is there any workaround? Is it going to be implemented?

**Comment by argneshu** [comment]
0
down vote
favorite
I am automating IOS app test cases using Appium. I have a scenario in which I have to identify.. i am on which screen so that I can close the screen

In broader view , we have a inapp notification in our app which get open in random way.

So I can handle these condition if I would be able to identify the current screen. I handle the same thing in Android using driver.currentActivity method

I need the some kind of same method for IOS apps

**Comment by vikramvi** [comment]
@TikhomirovSergey does latest Java client has any good workaround for this issue or you still look for particular element in iOS native app ?

Thanks,
Vikram

**Comment by SrinivasanTarget** [comment]
@vikramvi 
>ios doesn't have the concept of activities. as @bootstraponline pointed out, the best way to know you are on a given screen is to check for an element which is uniquely present on that screen

You have the answer above. Apple still don't have any such concepts.
